[package]
name = "rnd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = { version = "0.11.2" }


[dev-dependencies]
chrono = "0.4.19"
