// Automatically generated by flapigen
package com.example.rust;


public interface CheckAllTypesInCallbackArgs {


    void checkAllTypes1(short a0, byte a1, int a2, short a3, long a4, int a5, long a6, int a7);


    void checkAllTypes2(long a0, long a1, float a2, double a3, long a4, long a5);


    void checkFoo(Foo foo);


    void checkStr(String s);


    void checkPath(String s);


    void checkArray(Foo [] arr);


    void checkByteArray(byte [] arr);

}
