// Automatically generated by flapigen
package com.example.rust;


public final class CircularDepsA {

    public CircularDepsA(String a0) {
        mNativeObj = init(a0);
    }
    private static native long init(String a0);

    public final String a(CircularDepsB b) {
        long a0 = b.mNativeObj;
        String ret = do_a(mNativeObj, a0);

        JNIReachabilityFence.reachabilityFence1(b);

        return ret;
    }
    private static native String do_a(long self, long b);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ CircularDepsA(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}