// Automatically generated by flapigen
package com.example.rust;


public final class CircularDepsB {

    public CircularDepsB(double a0) {
        mNativeObj = init(a0);
    }
    private static native long init(double a0);

    public final String b(CircularDepsA a) {
        long a0 = a.mNativeObj;
        String ret = do_b(mNativeObj, a0);
        java.lang.ref.Reference.reachabilityFence(a);

        return ret;
    }
    private static native String do_b(long self, long a);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ CircularDepsB(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}