// Automatically generated by flapigen
package com.example.rust;


public final class EffectBuilder {

    public EffectBuilder() {
        mNativeObj = init();
    }
    private static native long init();

    public final EffectBuilder add_gamepad(Gamepad gamepad) {
        long a0 = gamepad.mNativeObj;
        gamepad.mNativeObj = 0;

        long ret = do_add_gamepad(mNativeObj, a0);
        EffectBuilder convRet = new EffectBuilder(InternalPointerMarker.RAW_PTR, ret);

        JNIReachabilityFence.reachabilityFence1(gamepad);

        return convRet;
    }
    private static native long do_add_gamepad(long self, long gamepad);

    public final java.lang.String [] tag() {
        java.lang.String [] ret = do_tag(mNativeObj);

        return ret;
    }
    private static native java.lang.String [] do_tag(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ EffectBuilder(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}