// Automatically generated by flapigen
package com.example.rust;


public final class FooWithLifetime {

    public FooWithLifetime() {
        mNativeObj = init();
    }
    private static native long init();

    public final void set_data(int v) {
        do_set_data(mNativeObj, v);
    }
    private static native void do_set_data(long self, int v);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ FooWithLifetime(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}