// Automatically generated by flapigen
package com.example.rust;


public final class LocationService {

    public static Position position() throws Exception {
        long ret = do_position();
        Position convRet = new Position(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_position() throws Exception;

    private LocationService() {}
}