// Automatically generated by flapigen
package com.example.rust;


public enum MyEnum {
    ITEM1(0),
    ITEM2(1),
    ITEM3(2);

    private final int value;
    MyEnum(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static MyEnum fromInt(int x) {
        switch (x) {
            case 0: return ITEM1;
            case 1: return ITEM2;
            case 2: return ITEM3;
            default: throw new Error("Invalid value for enum MyEnum: " + x);
        }
    }
}
