// Automatically generated by flapigen
package com.example.rust;


public final class Observable {

    public Observable() {
        mNativeObj = init();
    }
    private static native long init();

    public final void subscribe(MyObserver a0) {
        do_subscribe(mNativeObj, a0);
    }
    private static native void do_subscribe(long self, MyObserver a0);

    public final void change(int a0, String a1) {
        do_change(mNativeObj, a0, a1);
    }
    private static native void do_change(long self, int a0, String a1);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ Observable(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}