// Automatically generated by flapigen
package com.example.rust;


public final class OneStaticFunctionTest {

    public static native double f_hypot(double a0, double a1);

    private OneStaticFunctionTest() {}
}