// Automatically generated by flapigen
package com.example.rust;


public final class Position {

    private Position() {}

    public final java.util.Date timeStamp() {
        long ret = do_timeStamp(mNativeObj);
        java.util.Date convRet = new java.util.Date(ret);

        return convRet;
    }
    private static native long do_timeStamp(long self);

    public final double getLatitude() {
        double ret = do_getLatitude(mNativeObj);

        return ret;
    }
    private static native double do_getLatitude(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ Position(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}