// Automatically generated by flapigen
package com.example.rust;


public final class ReturnInCallbackTester {

    public static native void run(TestReturnInCallback cb);

    private ReturnInCallbackTester() {}
}