// Automatically generated by flapigen
package com.example.rust;


public final class Session {

    public Session() {
        mNativeObj = init();
    }
    private static native long init();

    public final String name() {
        String ret = do_name(mNativeObj);

        return ret;
    }
    private static native String do_name(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ Session(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}