// Automatically generated by flapigen
package com.example.rust;


public final class TestPathAndResult {

    public TestPathAndResult() throws Exception {
        mNativeObj = init();
    }
    private static native long init() throws Exception;

    public TestPathAndResult(String path) throws Exception {
        mNativeObj = init(path);
    }
    private static native long init(String path) throws Exception;

    public final String getPath() {
        String ret = do_getPath(mNativeObj);

        return ret;
    }
    private static native String do_getPath(long self);

    public final Boo getBoo() {
        long ret = do_getBoo(mNativeObj);
        Boo convRet = new Boo(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_getBoo(long self);

    public final Foo [] get_foo_list() {
        Foo [] ret = do_get_foo_list(mNativeObj);

        return ret;
    }
    private static native Foo [] do_get_foo_list(long self);

    public static native Foo [] get_result_foo_list(boolean generate_err) throws Exception;

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ TestPathAndResult(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
    public int javaFunc() { return 17; }

    public Boo[] testHandArrayReturn() { return do_testHandArrayReturn(this.mNativeObj); }
    private static native Boo[] do_testHandArrayReturn(long me);
}