// Automatically generated by flapigen
package com.example.rust;


public final class TestMultiThreadCallback {

    public static native void f(ThreadSafeObserver cb);

    private TestMultiThreadCallback() {}
}