// Automatically generated by flapigen
package com.example.rust;


public interface TestReturnInCallback {


    boolean f_bool(boolean x);


    byte f_i8(byte x);


    short f_i16(short x);


    int f_i32(int x);


    long f_i64(long x);


    float f_f32(float x);


    double f_f64(double x);

}
