// Automatically generated by flapigen
package com.example.rust;


public final class TestCheckAllTypesInCallbackArgs {

    public static native void call_cb(CheckAllTypesInCallbackArgs cb);

    private TestCheckAllTypesInCallbackArgs() {}
}